---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Yoann Morin"
keywords:    "Yoann Morin, Yoann, Morin, economics, agglomeration, agglomeration economies, urban economics, regional economics, regional science, urban, training, labour economics, growth, spatial econometrics, economic geography, growth, human capital, developmnent economics, development, mining, conflict, causal inference"
description: "Personnal page of Yoann Morin"
source_link: "https://github.com/t413/SinglePaged"
favicon:

touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:G-MC3E2VR1FK  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:      '#111111'
  white:      '#f8f8f8'
  brown:      '#cca978'
  anthracite: '#303030'
  taupe:      '#463f32'
  grey:       '#d6cecc'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'

kramdown:
  auto_ids:  false
